// Unit tests of the smoke-harness safety helpers. Pure: no network, no Supabase, no env access.
import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveSmokeConfig, SmokeGuardError, isSmokeEmail, newSmokeEmail, createRedactor, createCleanupLedger, createReporter, EMAIL_PREFIX } from './common.mjs';

const GOOD = { FORGE_ALLOW_8C_SMOKE_TEST: 'true', NEXT_PUBLIC_SUPABASE_URL: 'https://devproj.supabase.co', NEXT_PUBLIC_SUPABASE_ANON_KEY: 'anon-key-value-123',
  SUPABASE_SERVICE_ROLE_KEY: 'service-role-value-456', FORGE_SMOKE_SUPABASE_HOST: 'devproj.supabase.co' };
const problems = (env, opts) => { try { resolveSmokeConfig(env, opts); return []; } catch (e) { assert.ok(e instanceof SmokeGuardError); return e.problems; } };

test('env guard: the opt-in flag and every required variable are mandatory (fail-closed)', () => {
  assert.deepEqual(problems(GOOD), []);
  assert.match(problems({ ...GOOD, FORGE_ALLOW_8C_SMOKE_TEST: undefined }).join('|'), /FORGE_ALLOW_8C_SMOKE_TEST=true/);
  assert.match(problems({ ...GOOD, FORGE_ALLOW_8C_SMOKE_TEST: '1' }).join('|'), /FORGE_ALLOW_8C_SMOKE_TEST=true/);
  for (const name of ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'FORGE_SMOKE_SUPABASE_HOST'])
    assert.match(problems({ ...GOOD, [name]: '' }).join('|'), new RegExp(`Missing required env var ${name}`));
  assert.equal(problems({}).length >= 5, true, 'empty env reports every problem at once');
});
test('env guard: the LLM script needs its own opt-in and ANTHROPIC_API_KEY', () => {
  const p = problems(GOOD, { llm: true }).join('|');
  assert.match(p, /FORGE_ALLOW_8C_LLM_SMOKE_TEST=true/); assert.match(p, /ANTHROPIC_API_KEY/);
  assert.deepEqual(problems({ ...GOOD, FORGE_ALLOW_8C_LLM_SMOKE_TEST: 'true', ANTHROPIC_API_KEY: 'sk-ant-xxxxxxxxxxxx' }, { llm: true }), []);
});
test('production guard: NODE_ENV/VERCEL_ENV production, denylisted host, host mismatch and remote app URL are refused', () => {
  assert.match(problems({ ...GOOD, NODE_ENV: 'production' }).join('|'), /NODE_ENV=production/);
  assert.match(problems({ ...GOOD, VERCEL_ENV: 'production' }).join('|'), /VERCEL_ENV=production/);
  assert.match(problems({ ...GOOD, FORGE_SMOKE_PRODUCTION_SUPABASE_HOST: 'other.supabase.co, devproj.supabase.co' }).join('|'), /refusing to touch production/);
  assert.match(problems({ ...GOOD, FORGE_SMOKE_SUPABASE_HOST: 'prodproj.supabase.co' }).join('|'), /does not match/);
  assert.match(problems({ ...GOOD, FORGE_SMOKE_BASE_URL: 'https://forge.example.app' }).join('|'), /not local/);
  assert.deepEqual(problems({ ...GOOD, FORGE_SMOKE_BASE_URL: 'http://127.0.0.1:3001' }), []);
  assert.deepEqual(problems({ ...GOOD, FORGE_SMOKE_BASE_URL: 'https://staging.example.app', FORGE_SMOKE_ALLOW_REMOTE_BASE_URL: 'true' }), []);
});
test('test-user guard: only addresses generated by the script are accepted; real accounts never are', () => {
  const generated = newSmokeEmail('example.com', 'a');
  assert.ok(generated.startsWith(EMAIL_PREFIX)); assert.ok(isSmokeEmail(generated));
  for (const real of ['airanvlz@gmail.com', 'forge-8c-smoke@example.com', 'someone+forge-8c-smoke-abcdefgh@example.com', 'forge-8c-smoke-abcdefgh@', '', null, undefined, 42])
    assert.equal(isSmokeEmail(real), false, String(real));
  assert.notEqual(newSmokeEmail('example.com', 'a'), newSmokeEmail('example.com', 'a'));
  assert.match(problems({ ...GOOD, FORGE_SMOKE_EMAIL_DOMAIN: 'bad domain' }).join('|'), /EMAIL_DOMAIN/);
});
test('cleanup bookkeeping: only recorded entries are handled, in reverse order, failures never stop the rest', async () => {
  const ledger = createCleanupLedger(); const order = [];
  ledger.record('auth_user', 'auth-1', { email: 'x' }); ledger.record('athlete', 'FP-1', { authUserId: 'auth-1' });
  ledger.record('athlete', 'FP-2', { authUserId: 'auth-2' }); ledger.record('mystery', 'zzz');
  assert.equal(ledger.has('athlete', 'FP-1'), true); assert.equal(ledger.has('athlete', 'FP-9'), false);
  const report = await ledger.run({
    athlete: async e => { order.push(e.ref); if (e.ref === 'FP-2') throw new Error('boom'); return 'ok'; },
    auth_user: async e => { order.push(e.ref); return 'deleted'; },
  });
  assert.deepEqual(order, ['FP-2', 'FP-1', 'auth-1'], 'reverse order, unknown kind never executed');
  assert.deepEqual(report.map(r => r.ok), [false, false, true, true]);
  assert.match(report.find(r => r.kind === 'mystery').detail, /nothing deleted/);
  assert.equal(ledger.entries().length, 4, 'ledger is not mutated by cleanup');
});
test('secret redaction: keys, JWTs, bearer tokens and provider keys never reach the output', () => {
  const redact = createRedactor(['service-role-value-456', 'anon-key-value-123']);
  const jwt = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.abcdefghijklmnop';
  const out = redact(`key=service-role-value-456 anon=anon-key-value-123 Authorization: Bearer ${jwt} jwt ${jwt} sk-ant-api03-ABCDEF123 sb_secret_XYZ`);
  for (const secret of ['service-role-value-456', 'anon-key-value-123', jwt, 'ABCDEF123', 'XYZ']) assert.equal(out.includes(secret), false, secret);
  assert.match(out, /\[REDACTED/);
  assert.equal(redact('plain text'), 'plain text');
});
test('reporter: PASS/FAIL per stage, failures are collected and do not throw', async () => {
  const lines = [], r = createReporter(l => lines.push(l));
  assert.equal(await r.stage('ok stage', async () => 'detail'), true);
  assert.equal(await r.stage('bad stage', async () => { throw new Error('nope\nsecond line'); }), false);
  r.warn('w', 'careful');
  assert.deepEqual(r.summary(), { total: 2, passed: 1, failed: [{ name: 'bad stage', ok: false, error: 'nope\nsecond line' }] });
  assert.match(lines[0], /^PASS {2}ok stage — detail/); assert.match(lines[1], /^FAIL {2}bad stage — nope$/); assert.match(lines[2], /^WARN/);
});
