/** Editorial metadata only. Never imported by sports selection or dose authorities. */
export const movementLabels: Readonly<Record<string, string>> = {
  back_squat: 'Sentadilla trasera', front_squat: 'Sentadilla frontal', overhead_squat: 'Sentadilla con barra sobre la cabeza', box_squat: 'Sentadilla a cajón',
  goblet_squat: 'Sentadilla goblet', wall_ball: 'Lanzamiento de balón a la pared', thruster: 'Thruster con barra', pistol_squat: 'Sentadilla a una pierna',
  deadlift: 'Peso muerto', rdl: 'Peso muerto rumano', sumo_deadlift: 'Peso muerto sumo', kettlebell_swing: 'Balanceo con kettlebell', good_morning: 'Buenos días', single_leg_rdl: 'Peso muerto rumano a una pierna',
  snatch: 'Arrancada', power_snatch: 'Arrancada de potencia', hang_snatch: 'Arrancada desde suspensión', snatch_pull: 'Tirón de arrancada',
  clean_and_jerk: 'Cargada y dos tiempos', power_clean: 'Cargada de potencia', hang_clean: 'Cargada desde suspensión', clean_pull: 'Tirón de cargada',
  strict_press: 'Press estricto con barra', push_press: 'Press con impulso de piernas', push_jerk: 'Jerk con recepción en semiflexión', handstand_push_up: 'Flexiones de pino', pike_push_up: 'Flexiones en pica', db_shoulder_press: 'Press de hombros con mancuernas',
  bench_press: 'Press de banca', db_bench_press: 'Press de banca con mancuernas', push_up: 'Flexiones', dip: 'Fondos', pull_up: 'Dominadas', chest_to_bar: 'Dominadas con pecho a la barra', muscle_up: 'Muscle-up', ring_row: 'Remo en anillas', barbell_row: 'Remo con barra', toes_to_bar: 'Pies a la barra',
  box_jump: 'Salto al cajón', box_step_up: 'Subida al cajón', double_under: 'Saltos dobles de comba', single_under: 'Saltos simples de comba', burpee: 'Burpees', row_erg: 'Remo en ergómetro', bike_erg: 'Bicicleta ergométrica', ski_erg: 'Ergómetro de esquí', farmers_carry: 'Paseo del granjero', sled_push: 'Empuje de trineo',
  russian_twist: 'Giros rusos', hollow_hold: 'Hollow hold', gh_situp: 'Abdominales en GHD', knee_raise: 'Elevaciones de rodillas', plank: 'Plancha', v_up: 'Abdominales en V', sit_up: 'Abdominales', walking_lunge: 'Zancadas caminando', bulgarian_split_squat: 'Sentadilla búlgara', overhead_lunge: 'Zancada con carga sobre la cabeza',
  snatch_balance: 'Recepción de arrancada con impulso', drop_snatch: 'Recepción de arrancada sin impulso', muscle_snatch: 'Arrancada de fuerza', sotts_press: 'Press Sotts', clean_and_jerk_complex: 'Complejo de cargada y dos tiempos',
  bar_muscle_up: 'Muscle-up en barra', ring_muscle_up: 'Muscle-up en anillas', l_sit: 'Soporte en L', freestanding_handstand: 'Pino libre', handstand_hold: 'Mantenimiento de pino', handstand_shoulder_tap: 'Toques de hombro en pino', wall_walk: 'Caminata de manos hacia la pared', handstand_walk: 'Caminata de pino', strict_pull_up: 'Dominadas estrictas', deficit_hspu: 'Flexiones de pino con déficit', pike_handstand_push_up: 'Flexiones de pino en pica',
  assault_bike: 'Bicicleta Assault', echo_bike: 'Bicicleta Echo', run_400m: 'Carrera de 400 m', shuttle_run: 'Carrera de ida y vuelta', devil_press: 'Devil press', db_snatch: 'Arrancada con mancuerna', man_makers: 'Man makers con mancuernas', db_clean_and_jerk: 'Cargada y dos tiempos con mancuernas',
  sandbag_carry: 'Transporte de saco', yoke_carry: 'Transporte de yugo', gh_back_extension: 'Extensiones de espalda en GHD', sandbag_clean: 'Cargada con saco', sandbag_to_shoulder: 'Subida de saco al hombro', plate_ground_to_overhead: 'Disco del suelo sobre la cabeza', rope_climb: 'Subida a la cuerda', legless_rope_climb: 'Subida a la cuerda sin piernas', kipping_pull_up: 'Dominadas con kipping', knees_to_elbows: 'Rodillas a los codos', ring_dip: 'Fondos en anillas', strict_ring_dip: 'Fondos estrictos en anillas', hand_release_push_up: 'Flexiones soltando las manos', bar_facing_burpee: 'Burpees de frente a la barra', bar_over_burpee: 'Burpees sobre la barra',
  squat_clean: 'Cargada con sentadilla', hang_power_clean: 'Cargada de potencia desde suspensión', split_jerk: 'Jerk con recepción en tijera', power_jerk: 'Jerk de potencia', clean_high_pull: 'Tirón alto de cargada', snatch_high_pull: 'Tirón alto de arrancada',
  kb_clean: 'Cargada con kettlebell', kb_snatch: 'Arrancada con kettlebell', kb_push_press: 'Press con impulso con kettlebell', turkish_get_up: 'Levantamiento turco', kb_goblet_squat: 'Sentadilla goblet con kettlebell', kb_lunge: 'Zancada con kettlebell', kb_clean_and_press: 'Cargada y press con kettlebell',
  db_thruster: 'Thruster con mancuernas', db_push_press: 'Press con impulso con mancuernas', db_push_jerk: 'Jerk con mancuernas', db_deadlift: 'Peso muerto con mancuernas', db_step_up: 'Subida con mancuernas', db_front_rack_lunge: 'Zancada con mancuernas en posición frontal', db_lunge: 'Zancada con mancuernas', db_clean: 'Cargada con mancuernas', db_power_clean: 'Cargada de potencia con mancuernas', db_box_step_up: 'Subida al cajón con mancuernas', barbell_lunge: 'Zancada con barra', front_rack_lunge: 'Zancada con barra en posición frontal', jerk: 'Jerk',
  sled_drag: 'Arrastre de trineo', sled_pull: 'Tirón de trineo', overhead_carry: 'Transporte con carga sobre la cabeza', bear_hug_carry: 'Transporte de carga abrazada', med_ball_clean: 'Cargada con balón medicinal', med_ball_slam: 'Golpe de balón medicinal al suelo', med_ball_throw: 'Lanzamiento de balón medicinal', lateral_box_jump: 'Salto lateral al cajón', broad_jump: 'Salto horizontal', jumping_lunge: 'Zancadas con salto', tuck_jump: 'Salto con rodillas al pecho', lateral_jump: 'Salto lateral', burpee_box_jump: 'Burpee con salto al cajón', burpee_box_step_up: 'Burpee con subida al cajón',
  nordic_curl: 'Curl nórdico', calf_raise: 'Elevaciones de talones', hip_thrust: 'Empuje de cadera', bounding: 'Multisaltos de carrera', strides: 'Progresivos cortos', skipping_a: 'Skipping A', skipping_b: 'Skipping B', ankling: 'Pasos cortos de tobillo', back_squat_pausa: 'Sentadilla trasera con pausa', deficit_deadlift: 'Peso muerto con déficit', tempo_squat: 'Sentadilla con tempo', single_leg_box_squat: 'Sentadilla a una pierna a cajón', close_grip_bench: 'Press de banca con agarre cerrado',
  rodaje_z1: 'Rodaje en Z1', rodaje_z2: 'Rodaje en Z2', rodaje_largo: 'Rodaje largo', tempo_run: 'Carrera de umbral', series_umbral: 'Series de umbral', series_vo2max: 'Series de VO₂ máx.', fartlek: 'Fartlek', cuestas: 'Carrera en cuestas', sprint: 'Esprints', drills_tecnica: 'Ejercicios de técnica de carrera', progresivo: 'Carrera progresiva', regenerativo: 'Rodaje regenerativo',
};
export const methodLabels: Readonly<Record<string, string>> = {
  running_base: 'Rodaje aeróbico', running_long_run: 'Rodaje largo aeróbico', running_threshold: 'Umbral', running_specific: 'Resistencia específica', running_economy: 'Técnica de carrera', running_vo2: 'Intervalos de VO₂ máx.', running_recovery: 'Rodaje regenerativo',
  runner_support_strength: 'Fuerza para carrera', runner_posterior: 'Cadena posterior para carrera', runner_power: 'Potencia para carrera', box_aerobic: 'Trabajo aeróbico', box_support_strength: 'Fuerza de apoyo', box_max_strength: 'Fuerza máxima', box_posterior: 'Cadena posterior', box_power: 'Potencia', box_gymnastics: 'Trabajo gimnástico', box_mixed: 'Trabajo metabólico', box_weightlifting: 'Técnica de halterofilia', box_technique: 'Práctica técnica',
};
export const adaptationLabels: Readonly<Record<string, string>> = {
  fuerza_maxima: 'fuerza máxima', hipertrofia: 'hipertrofia', halterofilia_tecnica: 'técnica de halterofilia', halterofilia_soporte: 'fuerza de apoyo a la halterofilia', potencia: 'potencia', gimnasticos: 'trabajo gimnástico', capacidad_glucolitica: 'trabajo metabólico', capacidad_aerobica: 'capacidad aeróbica', cadena_posterior: 'cadena posterior', fuerza_general: 'fuerza', tecnica: 'técnica', coordinacion: 'coordinación', movilidad_tecnica: 'movilidad', recuperacion_activa: 'recuperación activa', base_aerobica: 'base aeróbica', umbral: 'umbral', vo2max: 'VO₂ máx.', velocidad: 'velocidad', economia_carrera: 'técnica y economía de carrera', potencia_carrera: 'potencia para carrera', resistencia_especifica: 'resistencia específica', fuerza_corredor: 'fuerza para carrera',
};
export const structureLabels: Readonly<Record<string, string>> = {
  amrap_corto: 'AMRAP corto', amrap_largo: 'AMRAP largo', emom_fuerza: 'EMOM de fuerza', emom_metcon: 'EMOM metabólico', for_time_corto: 'Trabajo por tiempo', for_time_medio: 'Trabajo por tiempo', chipper: 'Secuencia de ejercicios', ladder: 'Escalera de repeticiones', couplet: 'Combinación de dos ejercicios', triplet: 'Combinación de tres ejercicios', death_by: 'Progresión por minutos', strength_sets: 'Series de fuerza', complex_halterofilia: 'Complejo de halterofilia', intervalos_carrera: 'Intervalos de carrera', continuo_carrera: 'Carrera continua', potencia_series: 'Series de potencia', practica_habilidades: 'Práctica técnica', movilidad_controlada: 'Movilidad controlada', continuo_regenerativo: 'Rodaje regenerativo', velocidad_recuperacion_completa: 'Velocidad con recuperación', tecnica_carrera: 'Técnica de carrera', potencia_carrera_series: 'Series de potencia para carrera', fuerza_corredor_series: 'Series de fuerza para carrera', tempo_continuo: 'Carrera continua de umbral',
};
export const goalLabels: Readonly<Record<string, string>> = { running_general: 'carrera general', half_marathon: 'media maratón', '10k': '10 km', crossfit: 'rendimiento en CrossFit', max_strength: 'fuerza máxima', hyrox: 'Hyrox' };
export const phaseLabels: Readonly<Record<string, string>> = { accumulation: 'acumulación', intensification: 'intensificación', realization: 'realización', deload: 'descarga', unknown: 'fase sin resolver' };
export const roleLabels: Readonly<Record<string, string>> = { PRIMARY: 'principal', SUPPORTING: 'de apoyo', MAINTENANCE: 'de mantenimiento', OPTIONAL: 'opcional', RECOVERY: 'recuperación' };
export const metricLabels: Readonly<Record<string, string>> = { confirmedBaseZone: 'FC objetivo', z1: 'Z1', z2: 'Z2', z3: 'Z3', z4: 'Z4', z5: 'Z5', easyPace: 'Ritmo suave', thresholdPace: 'Ritmo umbral', easyHr: 'FC suave', thresholdHr: 'FC umbral', '5k': 'Ritmo 5 km', '10k': 'Ritmo 10 km' };
